SET SERVEROUTPUT ON
DECLARE
    V_SOMA_SALARIO  NUMBER(10,2);
    V_FNAME HR.EMPLOYEES.FIRST_NAME%TYPE;
    V_LNAME HR.EMPLOYEES.LAST_NAME%TYPE;
BEGIN
    SELECT  SUM(NVL(SALARY,0)) INTO V_SOMA_SALARIO
    FROM    HR.EMPLOYEES
    WHERE   DEPARTMENT_ID=10;
    DBMS_OUTPUT.PUT_LINE('A soma dos salários é: ' ||  V_SOMA_SALARIO); 
    
    SELECT  FIRST_NAME,LAST_NAME INTO V_FNAME, V_LNAME
    FROM    HR.EMPLOYEES
    WHERE   EMPLOYEE_ID = 100;
    DBMS_OUTPUT.PUT_LINE('O nome completo do empregado é: ' ||  V_FNAME || ' ' || V_LNAME); 
END;